name: DORA Log Event

on:
  push:
    branches: master

jobs:
  events:
    permissions: 
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Créer l'évènement de déploiement
        id: deployment
        uses: actions/github-script@v9
        with:
          script: |
            const d = await github.rest.repos.createDeployment({
              owner: context.repo.owner, repo: context.repo.repo,
              ref: context.sha, environment: 'production',
              required_contexts: [], auto_merge: false });
            return d.data.id;
      - name: "Log déploiment"
        run: |
          echo "Deploiement réussi cette fois-ci"
      